name: Unit Tests

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Node.js Environment
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install Dependencies
      run: npm install

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Node.js Environment
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Symbolizer Tests
      run: npx bun test symbolizer
    
    - name: Lexer Tests
      run: npx bun test lexer

    - name: Parser Tests
      run: npx bun test parser